### ISSUE TITLE
Failed to mount component: template or render function not defined. (found in root instance)

### ISSUE THREAD

**Issue by hee93** [dingyiming/vue2-start#26]
新手请教一下 这个是什么问题？

**Comment by dingyiming** [comment]
是说没有挂载的模板或者渲染函数，需要提供下你的具体代码了

**Comment by IMustTo** [comment]
@hee93 
这么写
``` javascript
new Vue({
  store,
  render: h => h(App),
}).$mount('#app');
```

**Comment by laughmaker** [comment]
https://github.com/vuejs/vue-loader/issues/287
这个解决

**Comment by eskrano** [comment]
http://stackoverflow.com/questions/39488660/vue-js-2-0-not-rendering-anything so fix for render

**Comment by benlightning** [comment]
new Vue({
        el: '#app',
        components: {
            'my-component': App
        },
        render: h => h(App)
    });
我遇到这个问题的解决只是加个了个 render: h => h(App)，没有export default {}; 也没有在webpackde config中添加resolve
